name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup toolchain
        run: sudo apt install build-essential gcc-mingw-w64-x86-64 zip
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile
        run: ./build_release.sh
      - name: Collect artifacts
        uses: actions/upload-artifact@v2
        with:
          name: 'plugin.zip'
          path: 'plugin.zip'
